name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm i --no-audit --no-fund

      - name: Optimize GIF for marketplace
        run: npm run optimize-gif

      - name: Derive version from tag
        id: vars
        run: echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Sync package.json version
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          TARGET_VERSION="${{ steps.vars.outputs.version }}"
          if [ "$CURRENT_VERSION" != "$TARGET_VERSION" ]; then
            npm version --no-git-tag-version $TARGET_VERSION
          else
            echo "Version already matches target: $CURRENT_VERSION"
          fi

      - name: Build
        run: npm run compile

      - name: Publish to VS Code Marketplace
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
        run: npx @vscode/vsce publish -p "$VSCE_TOKEN"

      - name: Publish to Open VSX
        env:
          OPEN_VSX_TOKEN: ${{ secrets.OPEN_VSX_TOKEN }}
        run: npx ovsx publish -p "$OPEN_VSX_TOKEN"


